dataset:
  name: "Ships_Optical"
  json_path: "${hydra:runtime.cwd}/data/Final_Fully_Cleaned_Ships[VHRShips_ShipsImageNet].json"
  image_root: "${hydra:runtime.cwd}/data/_Optical-Ship/VHRShips_ShipRSImageNEt/"
  num_classes: 5

model:
  architecture: "COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"

training:
  batch_size: 8
  learning_rate: 0.00025
  max_iterations: 120000
  num_workers: 8
  weight_decay: 0.0001
  steps: [40000, 80000, 110000]
  checkpoint_period: 10000
  focal_loss_gamma: 2.0
  focal_loss_alpha: 0.25
  batch_size_per_image: 512
  nms_thresh_train: 0.3
  pre_nms_topk_train: 10000
  post_nms_topk_train: 3000
  min_size_train: [800, 800]
  min_size_test: 800
  anchor_sizes: [[8], [16], [32], [64], [128], [256], [512]]
  anchor_ratios: [[0.5, 1.0, 2.0]]


output:
  dir: "../trained_models/Optical_Ships_v6[hydra_cluster]"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
