dataset:
  name: "Ships_Optical"
  json_path: "${hydra:runtime.cwd}/Final_Fully_Cleaned_Ships[VHRShips_ShipsImageNet].json"
  image_root: "${hydra:runtime.cwd}/_Optical-Ship/VHRShips_ShipRSImageNEt/"
  num_classes: 5  #

model:
  architecture: "COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"

training:
  batch_size: 2
  learning_rate: 0.0002
  max_iterations: 10
  num_workers: 4
  weight_decay: 0.0001

output:
  dir: "../trained_models/Optical_Ships_v6[hydraCluster]"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
